### ISSUE TITLE
Plugin not working as JS cannot be loaded

### ISSUE THREAD

**Issue by waza-ari** [bizley/Yii2-AjaxDropDown#1]
At last in case sensitive linux environment, the plugin is currently not working. The reason was quite hard to track down, but the solution is quite easy:

Rename `src/AjaxDropDown.min.js` to `src/AjaxDropdown.min.js`. I actually cannot really tell why, but after this renaming, the file was successfully retrieved and the plugin was working. Otherwise, the client could not fetch the min.js file, and the request returned an 404 error.

**Comment by bizley** [comment]
Fixed in https://github.com/bizley-code/Yii2-AjaxDropDown/releases/tag/1.2.1.1

Thanks!
