### ISSUE TITLE
How to set current value using JavaScript?

### ISSUE THREAD

**Issue by waza-ari** [bizley/Yii2-AjaxDropDown#2]
The DropDown is used to select an entry out of an ActiveRecord class. I am using the extra button to open a modal and to create a new entry on the fly, if it does not exist.

Both the (database) ID and the name of the new Entity is returned using JSON. Is there a way to pre-select data using Java-Script?

**Comment by bizley** [comment]
Currently there is no way of preselecting data using JS other than modifying manually DOM elements which varies based on singleMode and singleModeBottom parameters. I think I can add something like this in next release but currently I'm working on my Yii 2 forum project so I can not give you ETA on this.

**Comment by waza-ari** [comment]
Sounds great, I would love to see that feature. In the meantime, I will try to figure out which DOM elements need to be modified. I am using singleMode=true, and singleModeBottom=false.

Thanks and regards

**Comment by bizley** [comment]
For those parameters:
1) Show button.ajaxDropDownSingleRemove
2) Hide button.ajaxDropDownToggle
3) Set filter input value with the selected text
4) Set this field to 'disabled'
5) Add `<input class="singleResult" type="hidden" name="{name here}" value="{id here}">` after the filter input field

**Comment by waza-ari** [comment]
This is working, thank you. I still would love to see this as feature. So should I create a new issue as feature request?

**Comment by bizley** [comment]
Yes please.

**Comment by bizley** [comment]
You can find methods to manipulate selected results with JS in version 1.3 https://github.com/bizley-code/Yii2-AjaxDropDown/releases/tag/1.3
