### ISSUE TITLE
Preselected

### ISSUE THREAD

**Issue by andjelko** [bizley/Yii2-AjaxDropDown#3]
Preselected when $singleMode = fasle, don't working!

**Comment by bizley** [comment]
Could you paste here the widget configuration you are trying to run?

**Comment by andjelko** [comment]
echo AjaxDropdown::widget([
    'name' => 'WidgetTest123',
    'source' => Url::to(['datasource']),
    #'singleMode' => true,
    'data' => [
        [
            'id' => 1,
            'mark' => 1,
            'value' => 'asdasdas',
        ],
        [
            'id' => 3,
            'mark' => 1,
            'value' => 'record three',
        ],
    ]
]);

when I uncomment singleMode then preselect working for one data.

**Comment by bizley** [comment]
Thanks for pointing that. Cheers!
