### ISSUE TITLE
Ajax Dropdown is not working in modal popup (yii/bootstrap/Modal)

### ISSUE THREAD

**Issue by vilaskrish** [bizley/Yii2-AjaxDropDown#5]
I have used Ajaxdrop down in normal view page it is working fine and displaying drop down values also. But when i use this in Modalpopup It is not rendering the drop down value.

I have used renderPartial() method in controller to get the popup in the view page.

**Comment by bizley** [comment]
I guess binding the JS plugin higher in DOM should work. I need to check it first.

**Comment by bizley** [comment]
Actually it's not a problem with extension itself.
You should use `renderAjax` instead of `renderPartial` so all the scripts and styles can be loaded as well.

**Comment by vilaskrish** [comment]
thanks  bizley. It's working fine

**Comment by vilaskrish** [comment]
Is there any plugin available for open a modal popup in side modal popup?Or any other way to do this?
Can u let me know the solution?

**Comment by bizley** [comment]
I'm not sure if plugins like that exist. It shouldn't be difficult to modify the content of already displayed modal box to load another ajax content when a button is clicked. Google "replace content of div with jQuery".

**Comment by vilaskrish** [comment]
I have done opening two popups in a single page. I have used ajaxDropDownWidget in first modal popup and added extra button. If we click on that extra button second popup also opening. I entered all the data and click on submit the data is storing via jquery and closing the popup automatically. But added data is not coming to first modal popup ajaxDropDownWidget . Can u plase help me

$(document).ready(function () {
	$('form').on('submit', function () {
			var task_type_name = $('#tasktype-task_type_name').val();
			var task_type_desc = $('#tasktype-task_type_desc').val();
			event.preventDefault();
			if($(this).attr('id') == 'task-type-form') {  //some check
					$.ajax({
						url: $(this).attr('action'),
						type: 'post',
						data: {name:  task_type_name , desc:  task_type_desc},
						success: function(){
							alert('saved successfully');
							var dlg=$('#modal1').dialog({});
							dlg.dialog('close'); //hide popup  
							$('#form').unbind('submit').submit();
							$('.ajaxDropDownWidget').reload;
							alert("hii");
						},
					});  
				return false;
			}
		});
});

**Comment by bizley** [comment]
You are using `$('.ajaxDropDownWidget').reload;` here - what should it do? I don't recall adding anything like that for this plugin.
Anyway, there are few events you can use like: `add`, `removeOne` and `removeAll` so you can manipulate any AjaxDropDown field using JavaScript. For example how to use it see [Adding two results with JS using a button](https://github.com/bizley/Yii2-AjaxDropDown/blob/master/docs/EXAMPLES.md#adding-two-results-with-js-using-a-button)

**Comment by yusufjonc07** [comment]
cevwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwvvewvewvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\///////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\/////////////////////////\\\\\\\\\\\//////////////////\\\\\\\\\\\\\\\\\\\\\\\\\////////////////////////\\\\\\\\\\\\\\\\\\\\\\\/////////////////////////////////\\\\\\\\\\\\\\\\///////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\/////////////////////////\\\\\\\\\\\\\\\\\\\\\\//////////////////////////\\\\\\\\\\\\\\\\////////////\\\\\\\\\\\/////////////////\\\\\\\\\\\\\\\\\\\////////////////////\\\\\\\\\\\///////////////////////\\\\\\\\\\\\\\\\\\\\\\//////////////////\\\\\\\\\\\\\\\\\\\\\\\//////////////////////\\\\\\\\\\\\\\\\\\//////////////////\\\\\\\\\\\\\\\\\\\////////////////////\\\\\\\\\\\\\\\\\\\\\\/////\\\\\\\\\\\////////////////////\\\\\\\\\\\\\\\\\\\\\\/////////////////\\\\\\\\\\\\\\\\\\\\\/////////////////\\\\\\\\\\\\\\\\\\\\\\\///////////////
